apiVersion: apps/v1
kind: Deployment
metadata:
  name: wuzx-gateway
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wuzx-gateway
  template:
    metadata:
      labels:
        app: wuzx-gateway
    spec:
      containers:
        - name: wuzx-gateway
          image: $image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

---
apiVersion: v1
kind: Service
metadata:
  name: wuzx-gateway
  namespace: kube-ops
spec:
  ports:
    - port: 80
      targetPort: 80
      name: wuzx-gateway
  selector:
    app: wuzx-gateway